config/routes.rb
Rails.application.routes.draw do
  root 'short#index'
 	post 'short/index', to: 'short#shorten'

 	get ':hash', to: 'short#redirect'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/short_controller.rb
class ShortController < ApplicationController
  def index
  	
  end

  def shorten
		@link = Link.new(link_params)
		unless @link.original_url.include? "http"
		   @link.original_url = @link.original_url.prepend("http://")
		end

  	if @link.save
  		@user_link = @link.id.to_s(36)
  		render :success
  	end
  end

  def success
  	
  end

  def redirect
  	id = params[:hash].to_i(36)
		link = Link.find(id)
		redirect_to link.original_url
  end

  private
  def link_params
  	params.require(:link).permit(:original_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_helper.rb
module ShortHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/short/index.html.erb
<div class="form-box">
	<%= form_for :link, url: short_index_path do |form| %>
		<h1>Shortly</h1>
		<p>No longering since 2017</p>

		<%= form.text_field :original_url, :class => "form-input" %> <br>

		<%= form.submit "Shorten"%>
	<% end %>
</div>

app/views/short/success.html.erb
<div class="form-box">
	<div class="success-display">
		<p>Your link is: <%= @user_link %></p>
	</div>
</div>